CREATE TABLE IF NOT EXISTS code_de_la_route(
            id INTEGER PRIMARY KEY NOT NULL,
            platforme TEXT NOT NULL, -- envoituresimone.com , codedelaroute.fr, etc
            theme TEXT,
            series INTEGER, -- usager , securite, etc
            question_number INTEGER,
            question TEXT NOT NULL,
            contain_media BOOLEAN NOT NULL, -- true or false
            media_type TEXT, -- IMAGE, AUDIO, VIDEO
            media_name TEXT, -- Name of the media (ex: 1.1.jpeg, 3.10.mp4, etc)
            media_source TEXT, -- The name of the resource that will be searched in the computer
            options TEXT NOT NULL, -- The option that the user must choose
            multiple_answeres BOOLEAN, -- True if there are multiple answeres
            answere TEXT NOT NULL, -- A Text that answere the question
            explanation TEXT, -- the explanation of the answere
            last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

--
-- Series : 2
--

INSERT INTO code_de_la_route (platforme, theme, series, question_number, question, contain_media, media_type, media_name, media_source, options, multiple_answeres, answere, explanation)
VALUES
('envoituresimone.com', '', 2, 1, 'En chevauchant cette ligne continue pour dépasser le cycliste, je suis en infraction', true, 'video', '2.1.mp4', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/videos/attachments/000/000/509/large-mp4/00165qA.mp4?1534257163', '[{%22isAnswere%22:false,%22value%22:%22Oui%22},{%22isAnswere%22:true,%22value%22:%22Non%22},{%22isAnswere%22:true,%22value%22:%22J%27assure sa sécurité%22},{%22isAnswere%22:false,%22value%22:%22Aucun%22}]', true, 'Pour dépasser un cycliste, je dois laisser un intervalle suffisant pour prévenir tout risque d%27écart ou de perte d%27équilibre de sa part. Ce qui est plus probable que lorsque je dépasse une voiture.', 'Cette zone vers laquelle il pourrait se déporter, c%27est ce qu%27on appelle la ZONE D%27INCERTITUDE.

Alors pour le dépasser il est préférable de chevaucher la ligne continue afin de garantir sa sécurité.

S%27agit-il d%27une infraction ? Non. Pour dépasser un cycliste, c%27est autorisé. Et même recommandé !'),
('envoituresimone.com', '', 2, 2, 'La consommation combinée de cannabis et d%27alcool multiplie le risque d%27accident mortel par', true, 'image', '2.2.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/128/medium/00042qA.jpg?1534254528', '[{%22isAnswere%22:false,%22value%22:%224%22},{%22isAnswere%22:true,%22value%22:%2229%22},{%22isAnswere%22:false,%22value%22:%2224%22},{%22isAnswere%22:false,%22value%22:%2234%22}]', false, 'Plusieurs études montrent que l%27association cannabis et alcool est particulièrement dangereuse pour la conduite. Bien plus que chacun de ses produits pris séparément (qui sont déjà dangereux !).', 'On estime que le risque d%27accident mortel en ayant consommé ce cocktail multiplie le risque d%27accident par...29 !'),
('envoituresimone.com', '', 2, 3, 'Le risque le plus probable est ', true, 'image', '2.3.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/131/medium/00043qA.jpg?1534254543', '[{%22isAnswere%22:false,%22value%22:%22De recevoir une pierre sur la voiture%22},{%22isAnswere%22:true,%22value%22:%22Qu%27il y ait des pierres sur la chaussée%22}]', false, 'Les 2 risques existent : celui de recevoir une pierre sur la voiture, mais aussi de trouver des pierres déjà tombées.', 'Mais le plus probable est de trouver des pierres sur la route, ce qui peut être dangereux (risque d%27éclatement d%27un pneu par exemple).

Mais ce n%27est pas la peine de chercher les ennuis ! Si je stationne dans ce secteur, j%27augmente le risque de recevoir une pierre sur le toit. Voilà pourquoi il est préférable de stationner en dehors de cette zone.'),
('envoituresimone.com', '', 2, 3, 'Stationner dans cette zone est déconseillé', true, 'image', '2.3.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/131/medium/00043qA.jpg?1534254543', '[{%22isAnswere%22:true,%22value%22:%22Oui%22},{%22isAnswere%22:false,%22value%22:%22Non%22}]', false, 'Les 2 risques existent : celui de recevoir une pierre sur la voiture, mais aussi de trouver des pierres déjà tombées.', 'Mais le plus probable est de trouver des pierres sur la route, ce qui peut être dangereux (risque d%27éclatement d%27un pneu par exemple).

Mais ce n%27est pas la peine de chercher les ennuis ! Si je stationne dans ce secteur, j%27augmente le risque de recevoir une pierre sur le toit. Voilà pourquoi il est préférable de stationner en dehors de cette zone.'),
('envoituresimone.com', '', 2, 4, 'Un délit de fuite est passible : d%27une peine de prison allant jusqu%27à', true, 'image', '2.4.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/134/medium/00044qA.jpg?1534254559', '[{%22isAnswere%22:false,%22value%22:%221 an%22},{%22isAnswere%22:true,%22value%22:%223 an%22}]', false, 'Commettre un délit de fuite, c%27est provoquer un accident et s%27enfuir sans laisser d%27adresse.', 'Les sanctions sont extrêmement lourdes. Jusqu%27à 3 ans de prison et 75 000 € d%27amende.

Attention, le délit de fuite ne concerne pas que les accidents corporels. Si vous égratignez légèrement une voiture sur un parking et que vous ne laissez pas vos coordonnées, il s%27agit aussi d%27un délit de fuite !'),
('envoituresimone.com', '', 2, 4, 'Un délit de fuite est passible : d%27une amende pouvant coûter jusqu%27à', true, 'image', '2.4.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/134/medium/00044qA.jpg?1534254559', '[{%22isAnswere%22:false,%22value%22:%2215 000€%22},{%22isAnswere%22:true,%22value%22:%2275 000€%22}]', false, 'Commettre un délit de fuite, c%27est provoquer un accident et s%27enfuir sans laisser d%27adresse.', 'Les sanctions sont extrêmement lourdes. Jusqu%27à 3 ans de prison et 75 000 € d%27amende.

Attention, le délit de fuite ne concerne pas que les accidents corporels. Si vous égratignez légèrement une voiture sur un parking et que vous ne laissez pas vos coordonnées, il s%27agit aussi d%27un délit de fuite !'),
('envoituresimone.com', '', 2, 5, 'Pour être mieux vu, j%27allume les feux de brouillard', true, 'image', '2.5.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/137/medium/00045qA.jpg?1534254574', '[{%22isAnswere%22:false,%22value%22:%22avant%22},{%22isAnswere%22:false,%22value%22:%22arrière%22},{%22isAnswere%22:true,%22value%22:%22Aucun%22}]', false, 'Il a dû neiger il y a peu de temps, mais il ne neige plus. Et la visibilité est plutôt bonne !', 'Donc interdiction d%27allumer les feux de brouillard, que ce soit devant ou derrière. Si je veux que ma voiture soit mieux visible, ce qui peut être une bonne chose surtout si sa couleur peut se confondre avec la neige, j%27allume les feux de croisement. C%27est autorisé, même par temps clair, et ils suffisent amplement.'),
('envoituresimone.com', '', 2, 6, 'Un manque d%27huile moteur entraîne', true, 'image', '2.6.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/140/medium/00046qA.jpg?1534254591', '[{%22isAnswere%22:true,%22value%22:%22une surchauffe du moteur%22},{%22isAnswere%22:true,%22value%22:%22une casse du moteur%22},{%22isAnswere%22:false,%22value%22:%22Aucun%22}]', true, 'L%27huile assure la lubrification de tout le moteur. Accessoirement, sa circulation participe aussi à son refroidissement.', 'Un manque d%27huile peut rapidement avoir des conséquences graves et irréversibles : certaines pièces ne sont plus lubrifiées, s%27échauffent, se grippent et cassent. La facture est généralement salée... si la réparation en vaut le coup !

Niveau à surveiller régulièrement !'),
('envoituresimone.com', '', 2, 7, 'A 90 km/h : je parcours environ', true, 'image', '2.7.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/143/medium/00047qA.jpg?1534254609', '[{%22isAnswere%22:false,%22value%22:%2218 mètres par seconde%22},{%22isAnswere%22:true,%22value%22:%2225 mètres par seconde%22}]', false, 'Pour calculer approximativement ma vitesse en mètres par seconde, il suffit de prendre le chiffre des dizaines de ma vitesse en km/h et de le multiplier par 3. Ici : je multiplie le %229%22 de %2290%22 par 3, ce qui me donne 27. Ma vitesse est donc approximativement de 25 m/s, en arrondissant.', 'Mais l%27intervalle de sécurité minimum avec le véhicule qui me précède n%27est pas d%27une seconde, ce qui serait trop juste, mais de 2 secondes. Soit 25 m multipliés par 2, soit 50 mètres.'),
('envoituresimone.com', '', 2, 7, 'A 90 km/h : je laisse un intervalle minimum avec le véhicule devant moi d%27environ', true, 'image', '2.7.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/143/medium/00047qA.jpg?1534254609', '[{%22isAnswere%22:true,%22value%22:%2250 mètres%22},{%22isAnswere%22:false,%22value%22:%22100 mètres%22}]', false, 'Pour calculer approximativement ma vitesse en mètres par seconde, il suffit de prendre le chiffre des dizaines de ma vitesse en km/h et de le multiplier par 3. Ici : je multiplie le %229%22 de %2290%22 par 3, ce qui me donne 27. Ma vitesse est donc approximativement de 25 m/s, en arrondissant.', 'Mais l%27intervalle de sécurité minimum avec le véhicule qui me précède n%27est pas d%27une seconde, ce qui serait trop juste, mais de 2 secondes. Soit 25 m multipliés par 2, soit 50 mètres.'),
('envoituresimone.com', '', 2, 8, 'Un coffre de toit a une influence', true, 'image', '2.8.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/146/medium/00048qA.jpg?1534254631', '[{%22isAnswere%22:true,%22value%22:%22sur la consommation de carburant%22},{%22isAnswere%22:false,%22value%22:%22sur le temps de réaction%22},{%22isAnswere%22:true,%22value%22:%22sur le freinage%22},{%22isAnswere%22:true,%22value%22:%22sur la prise au vent%22}]', true, 'Un coffre de toit perturbe l%27écoulement de l%27air autour de la voiture. Il augmente la prise au vent. Cela a forcément une répercussion sur la consommation de carburant, qui augmente, surtout si je circule à allure rapide (hors agglomération). Sur autoroute, la consommation peut augmenter de 10%.', 'Mais ce n%27est pas son seul effet néfaste : placé en hauteur, s%27il est lourdement chargé, il risque de déséquilibrer la voiture lors des freinages... et surtout en virages !

Il favorise aussi les écarts en cas de vent latéral.

Je dois donc éviter de circuler avec un coffre de toit vide, qui ne sert à rien...et le charger de préférence avec des choses encombrantes, mais légères !'),
('envoituresimone.com', '', 2, 9, 'Le croisement est impossible. La voiture rouge doit reculer', true, 'image', '2.9.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/149/medium/00049qA.jpg?1534254654', '[{%22isAnswere%22:false,%22value%22:%22Oui%22},{%22isAnswere%22:true,%22value%22:%22Non%22}]', false, 'Lorsque 2 véhicules se croisent en déclivité et que le croisement est impossible, c%27est au véhicule descendant de manoeuvrer pour faciliter le passage.', 'Si ce sont 2 véhicules de catégories différentes, c%27est le plus manoeuvrable des 2 qui doit reculer. Il n%27y a plus de montée ou de descente qui tienne.

Ici, même si le car est plus gros, il est plus manoeuvrable que la voiture attelée de la caravane.

C%27est donc au car de reculer et non à la voiture rouge.'),
('envoituresimone.com', '', 2, 10, 'Qui est correctement attaché', true, 'image', '2.10.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/152/medium/00050qA.jpg?1534254674', '[{%22isAnswere%22:true,%22value%22:%22Le passager N°1%22},{%22isAnswere%22:false,%22value%22:%22Le passager N°2%22},{%22isAnswere%22:false,%22value%22:%22Le passager N°3%22},{%22isAnswere%22:false,%22value%22:%22Le passager N°4%22}]', false, 'Le passager N°2 fait passer la ceinture de sécurité sous son bras. En cas d%27accident, elle sera moins efficace et il risque des blessures inutiles. Il n%27est donc pas correctement attaché.', 'Le passager N°3 a bouclé la ceinture correctement. Mais il est trop petit et la ceinture risque de le blesser au niveau du cou. Il devrait être installé sur un rehausseur.

Le passager N°4 a sa ceinture vrillée. Cas malheureusement fréquent. En cas d%27accident, là encore, la ceinture risque de le blesser au lieu de le protéger efficacement : la zone la plus étroite ainsi formée engendrera une pression plus forte sur le corps.

Le seul qui est bien installé, c%27est le passager N°1 : la ceinture le retient efficacement sans risquer de le blesser : posée bien à plat, bien tendue, sans risque de blessures au cou.'),
('envoituresimone.com', '', 2, 11, 'Les trajets faits quotidiennement entraînent généralement', true, 'image', '2.11.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/155/medium/00051qA.jpg?1534254696', '[{%22isAnswere%22:true,%22value%22:%22une baisse de la concentration%22},{%22isAnswere%22:true,%22value%22:%22une baisse de la concentration%22},{%22isAnswere%22:false,%22value%22:%22Aucun%22}]', true, 'On pourrait penser que sur un trajet que l%27on emprunte régulièrement, le risque d%27accident est moins élevé. Pourtant, c%27est le contraire.', 'En effet, lorsque l%27on croit bien connaître les endroits dangereux, cela procure un sentiment de sécurité, et l%27attention se relâche.

En conséquence, on circule plus vite là où l%27on pense qu%27il n%27y a pas, ou peu de dangers. Ainsi, en cas d%27imprévu, la marge de manoeuvre est réduite, le risque d%27accident augmente. Et si un accident survient, il est aussi plus violent. Donc plus grave.'),
('envoituresimone.com', '', 2, 12, 'Le seul facteur que je peux contrôler dans un virage, c%27est', true, 'image', '2.12.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/158/medium/00052qA.jpg?1534254714', '[{%22isAnswere%22:false,%22value%22:%22le rayon du virage%22},{%22isAnswere%22:false,%22value%22:%22l%27adhérence%22},{%22isAnswere%22:true,%22value%22:%22la vitesse%22},{%22isAnswere%22:false,%22value%22:%22le poids%22}]', false, 'Ces 4 paramètres ont une influence sur la tenue de route.', 'Mais le seul facteur que je peux faire varier dans un virage, c%27est la vitesse.

Le poids dépend du véhicule et de son chargement, et je ne peux rien y faire en arrivant dans le virage, pas plus que je ne peux changer quoi que ce soit à son rayon (sa courbure) ou à l%27adhérence.'),
('envoituresimone.com', '', 2, 13, 'Cette étiquette me permet de connaître', true, 'image', '2.13.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/161/medium/00053qA.jpg?1534254731', '[{%22isAnswere%22:false,%22value%22:%22la pression de gonflage d%27un pneu%22},{%22isAnswere%22:true,%22value%22:%22le bruit émis par un pneu%22},{%22isAnswere%22:false,%22value%22:%22Aucun%22}]', false, 'Cette étiquette, obligatoire pour les pneus neufs, me permet de connaître les performances d%27un pneu, afin de le comparer à d%27autres :', '- son indice de consommation, à ne pas négliger ; en effet, certains pneus entraînent une surconsommation de carburant importante,

- son adhérence sur sol humide ; très importante puisque les écarts observés d%27un pneu à l%27autre lors de freinages peuvent varier de plusieurs dizaines de mètres selon les modèles,

- le bruit qu%27il émet, à prendre en compte pour le confort des occupants mais aussi pour le bien-être des riverains ; le bruit des pneus peut être plus fort que le bruit du moteur !

En revanche, cette étiquette ne donne aucune indication concernant la pression de gonflage. Cette valeur dépend du véhicule sur lequel il sera monté.'),
('envoituresimone.com', '', 2, 14, 'Une fois ce camion dépassé, je devrai rester dans cette voie', true, 'image', '2.14.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/164/medium/00054qA.jpg?1534254748', '[{%22isAnswere%22:true,%22value%22:%22Oui%22},{%22isAnswere%22:false,%22value%22:%22Non%22}]', false, 'Je suis en cours de dépassement.', 'Généralement, une fois le véhicule dépassé, je dois revenir dans la voie la plus à droite.

Mais ici, cette voie est délimitée par un marquage large. Quelle est sa signification ?

Il délimite une voie réservée à certains usagers. Sur ce type de route, il s%27agit sans doute d%27une voie réservée aux véhicules lents ; c%27est-à-dire ceux dont la vitesse ne dépasse pas 60 km/h.

Je devrai donc rester dans la voie où je me trouve actuellement.'),
('envoituresimone.com', '', 2, 15, 'En cas de contrôle, le certificat d%27assurance, collé sur le pare-brise, me dispense de présenter l%27attestation d%27assurance', true, 'image', '2.15.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/167/medium/00055qA.jpg?1534254765', '[{%22isAnswere%22:false,%22value%22:%22Oui%22},{%22isAnswere%22:true,%22value%22:%22Non%22}]', false, 'Le certificat d%27assurance, la petite vignette verte collée en bas à droite du pare-brise, ne suffit pas à lui seul en cas de contrôle.', 'Si je me fais arrêter, je dois être en mesure de présenter immédiatement l%27attestation d%27assurance, où figurent d%27autres renseignements (entre autres, le nom de l%27assuré).

Si je ne peux pas la présenter, je risque une amende.'),
('envoituresimone.com', '', 2, 16, 'Les principales fonctions du dispositif d%27échappement sont', true, 'image', '2.16.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/170/medium/00056qA.jpg?1534254783', '[{%22isAnswere%22:true,%22value%22:%22De réduire le bruit du moteur%22},{%22isAnswere%22:true,%22value%22:%22De limiter la pollution atmosphérique%22},{%22isAnswere%22:false,%22value%22:%22Aucun%22}]', true, 'Sur certaines voitures, le pot d%27échappement est presque considéré comme un objet d%27art tant il est mis en valeur.', 'Ce serait oublier ses 2 fonctions essentielles : réduire la pollution (c%27est le rôle du catalyseur) et réduire le bruit du moteur. Sur le certificat d%27immatriculation, le niveau de bruit du véhicule est noté. Il est donc facile de le contrôler pour les forces de l%27ordre. Attention en cas de changement de pot, même soi-disant %22homologué%22 !'),
('envoituresimone.com', '', 2, 17, 'En 1 heure, l%27organisme élimine environ', true, 'image', '2.17.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/173/medium/00057qA.jpg?1534254799', '[{%22isAnswere%22:false,%22value%22:%220,05 g d%27alcool par litre de sang%22},{%22isAnswere%22:true,%22value%22:%220,15 g d%27alcool par litre de sang%22},{%22isAnswere%22:false,%22value%22:%220,25 g d%27alcool par litre de sang%22},{%22isAnswere%22:false,%22value%22:%220,50 g d%27alcool par litre de sang%22}]', false, 'Il faut du temps à l%27organisme pour éliminer l%27alcool que l%27on a absorbé. En effet, le corps n%27est capable d%27éliminer que 0,15 g d%27alcool en 1 heure. Soit environ 2 heures par verre (0,30 g d%27alcool par litre de sang).', 'C%27est essentiellement le foie qui se charge de cette élimination, et il n%27y a aucune solution efficace pour l%27accélérer.'),
('envoituresimone.com', '', 2, 18, 'Je poursuis le dépassement', true, 'image', '2.18.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/176/medium/00058qA.jpg?1534254816', '[{%22isAnswere%22:false,%22value%22:%22Oui%22},{%22isAnswere%22:true,%22value%22:%22Non%22}]', false, 'La flèche située au milieu de la voie où je circule me concerne. Il s%27agit certainement de la première puisque aucune autre n%27est visible dans le rétroviseur.', 'Cependant, je ne peux pas poursuivre ce dépassement, même si cela pourrait être tentant. En effet, où vais-je me rabattre ? Entre les voitures ? Impossible, les intervalles de sécurité, déjà trop justes, ne seraient plus du tout respectés. Et je n%27aurai pas le temps de dépasser ces 3 voitures en une seule fois.

Je me rabats immédiatement.'),
('envoituresimone.com', '', 2, 19, 'En agglomération, pour croiser ou dépasser des piétons, il est préférable de laisser un intervalle de', true, 'video', '2.19.mp4', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/videos/attachments/000/000/497/large-mp4/00162qA.mp4?1534256790', '[{%22isAnswere%22:false,%22value%22:%22moins d%27un mètre%22},{%22isAnswere%22:false,%22value%22:%22un mètre, pas plus%22},{%22isAnswere%22:true,%22value%22:%22plus d%27un mètre%22}]', false, 'Pourquoi y a-t-il une distance latérale minimum à laisser lorsque l%27on croise des usagers fragiles (piétons, %22deux-roues%22) ?', 'D%27une part, parce qu%27ils sont fragiles... et que le moindre accrochage risque d%27être grave. Mais aussi parce qu%27ils sont plus enclins à faire un écart ou à perdre l%27équilibre. C%27est ce qu%27on appelle leur ZONE D%27INCERTITUDE.

C%27est pourquoi, lorsque la situation le permet, et même si la réglementation ne m%27impose qu%27un mètre minimum en agglomération, je laisse plus que cet intervalle : pour avoir une marge en cas d%27imprévu.'),
('envoituresimone.com', '', 2, 20, 'Je me suis trompé de direction. Je retourne dans la voie de droite', true, 'image', '2.20.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/panoramic_images/attachments/000/000/182/medium/00060qA.jpg?1534254847', '[{%22isAnswere%22:false,%22value%22:%22Oui%22},{%22isAnswere%22:true,%22value%22:%22Non%22}]', false, 'Je suis dans une voie qui tourne à gauche.', 'Si je me suis trompé de direction, hors de question de revenir dans la voie de droite. Dans mon rétroviseur droit, je peux voir qu%27une voiture s%27apprête à me dépasser par la droite (c%27est autorisé dans ce cas).

Pour ne pas prendre de risques, je tourne à gauche, et je verrai pour faire demi-tour un peu plus loin. A un rond-point par exemple, l%27endroit le plus sûr, où à défaut, dans une intersection ou dans une rue large et sans circulation.'),
('envoituresimone.com', '', 2, 21, 'L%27appui-tête est essentiellement un élément', true, 'image', '2.21.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/185/medium/00061qA.jpg?1534254862', '[{%22isAnswere%22:false,%22value%22:%22De confort%22},{%22isAnswere%22:true,%22value%22:%22De sécurité%22}]', false, 'A part si l%27on fait un petit somme dans la voiture (donc à l%27arrêt !), la tête ne doit pas être en contact avec l%27appui-tête. On ne peut donc pas dire qu%27il s%27agit d%27un accessoire de confort...', 'Mais alors à quoi sert-il ?

C%27est un accessoire de sécurité. Il évite, lors d%27un choc arrière, que la tête ne parte violemment en arrière, au risque de se briser la nuque.

Il sert aussi en cas de choc avant : le corps est alors projeté vers l%27avant, puis revient brutalement en place. La tête part alors en arrière s%27il n%27y a pas l%27appui-tête pour la retenir. C%27est ce qu%27on appelle le %22coup du lapin%22, et il peut être mortel.

Dans mon installation au poste de conduite, je dois donc m%27assurer qu%27il est bien réglé : ni trop haut (il ne doit pas dépasser le haut de mon crâne), ni trop bas (il ne doit pas m%27arriver au niveau de la nuque).'),
('envoituresimone.com', '', 2, 21, 'Je vérifie que l%27appui-tête est bien réglé avant de partir', true, 'image', '2.21.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/185/medium/00061qA.jpg?1534254862', '[{%22isAnswere%22:true,%22value%22:%22Oui%22},{%22isAnswere%22:false,%22value%22:%22Non%22}]', false, 'A part si l%27on fait un petit somme dans la voiture (donc à l%27arrêt !), la tête ne doit pas être en contact avec l%27appui-tête. On ne peut donc pas dire qu%27il s%27agit d%27un accessoire de confort...', 'Mais alors à quoi sert-il ?

C%27est un accessoire de sécurité. Il évite, lors d%27un choc arrière, que la tête ne parte violemment en arrière, au risque de se briser la nuque.

Il sert aussi en cas de choc avant : le corps est alors projeté vers l%27avant, puis revient brutalement en place. La tête part alors en arrière s%27il n%27y a pas l%27appui-tête pour la retenir. C%27est ce qu%27on appelle le %22coup du lapin%22, et il peut être mortel.

Dans mon installation au poste de conduite, je dois donc m%27assurer qu%27il est bien réglé : ni trop haut (il ne doit pas dépasser le haut de mon crâne), ni trop bas (il ne doit pas m%27arriver au niveau de la nuque).'),
('envoituresimone.com', '', 2, 22, 'En période probatoire, l%27alcoolémie est sanctionnée à partir de', true, 'image', '2.22.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/188/medium/00062qA.jpg?1534254879', '[{%22isAnswere%22:true,%22value%22:%220,10 mg d%27alcool par litre d%27air expiré%22},{%22isAnswere%22:false,%22value%22:%220,15 mg d%27alcool par litre d%27air expiré%22},{%22isAnswere%22:false,%22value%22:%220,20 mg d%27alcool par litre d%27air expiré%22},{%22isAnswere%22:false,%22value%22:%220,50 mg d%27alcool par litre d%27air expiré%22}]', false, 'Le taux maximal d%27alcool dans le sang ne doit pas atteindre 0,50 g par litre de sang. Ce qui correspond à 0,25 mg d%27alcool par litre d%27air expiré (mesuré avec un éthylotest).', 'Pour les conducteurs en période probatoire, le seuil fixé est plus bas : 0,20 g d%27alcool par litre de sang. Ce qui correspond à 0,10 mg d%27alcool par litre d%27air expiré.'),
('envoituresimone.com', '', 2, 23, 'L%27intervalle de sécurité avec la voiture devant moi est suffisant si je circule à', true, 'image', '2.23.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/191/medium/00063qA.jpg?1534254893', '[{%22isAnswere%22:false,%22value%22:%2270 km/h%22},{%22isAnswere%22:false,%22value%22:%2230 km/h%22},{%22isAnswere%22:true,%22value%22:%22Aucun%22}]', false, 'Quelle est la signification de ce marquage devant moi, en forme de V renversé ?', 'Il s%27agit d%27un chevron. Un dispositif qui me permet de vérifier que l%27intervalle avec le véhicule devant moi est suffisant. Quelle que soit ma vitesse.

Ici, je n%27en vois qu%27un. Or, je devrais en voir 2. Donc, que je circule à 70 km/h ou à 30 km/h, je suis trop près de la voiture qui me précède.'),
('envoituresimone.com', '', 2, 24, 'Ces commandes permettent d%27ajuster', true, 'image', '2.24.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/194/medium/00064qA.jpg?1534254910', '[{%22isAnswere%22:false,%22value%22:%22le volume de la radio%22},{%22isAnswere%22:true,%22value%22:%22le régulateur et le limiteur de vitesse%22}]', false, 'Toutes les commandes qui comportent un signe plus et un signe moins ne concernent pas l%27autoradio ! (Contrôle du volume, ajustement des stations).', 'Ici, cela concerne le régulateur de vitesse (mais aussi le limiteur puisque son symbole figure également).

On trouve généralement l%27indication %22SET%22 (= fixer en Anglais).

S%27il est activé, le + permet d%27augmenter l%27allure programmée, et le moins de la diminuer.

Pour le désactiver, une simple pression sur le frein suffit.'),
('envoituresimone.com', '', 2, 25, 'J%27accélère', true, 'video', '2.25.mp4', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/videos/attachments/000/000/517/large-mp4/00167qA.mp4?1534257418', '[{%22isAnswere%22:false,%22value%22:%22Oui%22},{%22isAnswere%22:true,%22value%22:%22Non%22}]', false, 'J%27ai vu le feu passer au vert. Ce qui écarte normalement qu%27il ne repasse au rouge immédiatement. L%27occasion d%27accélérer ?', 'Surtout pas ! Il y a des intersections. Même si c%27est normalement à moi de passer, je dois faire preuve de prudence et de bon sens. Une intersection est un endroit dangereux. Et si mon feu vient de passer au vert, cela signifie que l%27autre feu vient tout juste de passer au rouge. Or, c%27est au début d%27un feu rouge que le risque qu%27un autre usager le franchisse est le plus élevé.

Si j%27arrive trop vite, non seulement je ne pourrai pas éviter la collision... mais en plus ses conséquences seront graves.'),
('envoituresimone.com', '', 2, 26, 'A partir de la première mise en circulation d%27une voiture, le premier contrôle technique doit intervenir au plus tard', true, 'image', '2.26.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/200/medium/00066qA.jpg?1534254954', '[{%22isAnswere%22:false,%22value%22:%22Avant 2 ans%22},{%22isAnswere%22:true,%22value%22:%22Avant 4 ans%22}]', false, 'Le 1er contrôle technique d%27une voiture doit intervenir avant le 4ème anniversaire de sa mise en circulation.', 'Ensuite, il doit être renouvelé tous les 2 ans, quelle que soit la distance parcourue.

Attention : pour vendre un véhicule de plus de 4 ans, le contrôle technique doit avoir moins de 6 mois.'),
('envoituresimone.com', '', 2, 26, 'Il doit ensuite être renouvelé', true, 'image', '2.26.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/200/medium/00066qA.jpg?1534254954', '[{%22isAnswere%22:false,%22value%22:%22Tous les ans%22},{%22isAnswere%22:true,%22value%22:%22Tous les 2 ans%22}]', false, 'Le 1er contrôle technique d%27une voiture doit intervenir avant le 4ème anniversaire de sa mise en circulation.', 'Ensuite, il doit être renouvelé tous les 2 ans, quelle que soit la distance parcourue.

Attention : pour vendre un véhicule de plus de 4 ans, le contrôle technique doit avoir moins de 6 mois.'),
('envoituresimone.com', '', 2, 27, 'Ce panneau peut être mis en place à proximité', true, 'image', '2.27.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/203/medium/00067qA.jpg?1534254967', '[{%22isAnswere%22:true,%22value%22:%22d%27une école%22},{%22isAnswere%22:true,%22value%22:%22d%27un centre de loisirs%22},{%22isAnswere%22:false,%22value%22:%22Aucun%22}]', true, 'Ce panneau n%27annonce pas un passage pour piétons, puisqu%27il existe un panneau pour cela, mais un endroit fréquenté par des enfants.', 'Il peut s%27agir d%27une école bien sûr, mais aussi d%27un centre de loisirs ou sportif, d%27un arrêt de car scolaire, ou encore d%27une aire de jeux.

Je risque donc de rencontrer des enfants, quel que soit le jour de la semaine, y compris tôt le matin ou assez tard, alors qu%27il fait déjà nuit.'),
('envoituresimone.com', '', 2, 28, 'Si la circulation alternée est décrétée pour cause de pollution, ce véhicule catalysé peut circuler les jours', true, 'image', '2.28.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/206/medium/00068qA.jpg?1534254980', '[{%22isAnswere%22:false,%22value%22:%22pairs%22},{%22isAnswere%22:true,%22value%22:%22impairs%22},{%22isAnswere%22:false,%22value%22:%22Aucun%22}]', false, 'Afin de limiter la pollution déjà existante, Il arrive que la circulation alternée soit décrétée.', 'Ma voiture peut être concernée : si elle ne fonctionne qu%27à l%27essence ou qu%27au gazole et qu%27elle est munie d%27un pot catalytique ; sans ce dispositif, j%27ai tout simplement interdiction de circuler pendant toute la période de restriction.

Je dois me référer aux numéros de la plaque d%27immatriculation. Si le dernier chiffre est pair (ou le dernier chiffre du bloc de gauche pour les anciennes plaques), je ne peux circuler que les jours pairs (le 2, 4, 6... 18... 30 du mois).

Ici, le dernier chiffre de ma plaque est impair (le 1), je suis donc autorisé à circuler les jours impairs uniquement.

Les autres jours, je devrai utiliser un véhicule autorisé, ou mieux : marcher, prendre mon vélo, utiliser les transports en commun... ou opter pour le covoiturage.'),
('envoituresimone.com', '', 2, 29, 'Sur l%27autoroute, les 2 principales causes des collisions en chaînes sont:', true, 'image', '2.29.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/209/medium/00069qA.jpg?1534254999', '[{%22isAnswere%22:true,%22value%22:%22La vitesse%22},{%22isAnswere%22:true,%22value%22:%22Le non-respect des intervalles de sécurité%22},{%22isAnswere%22:false,%22value%22:%22Le brouillard%22}]', true, 'On entend parfois ou on peut lire dans la presse que le brouillard a provoqué un carambolage... Comme s%27il s%27agissait d%27une fatalité !', 'Le brouillard, il se voit. En effet, il augmente le risque d%27accident... Mais il existe des parades. A commencer par réduire sa vitesse et augmenter les intervalles de sécurité.

La vitesse et le non-respect des intervalles de sécurité sont les 2 principales causes de collisions en chaîne sur l%27autoroute, et pas seulement par temps de brouillard.'),
('envoituresimone.com', '', 2, 30, 'La signalisation autorise le dépassement', true, 'image', '2.30.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/212/medium/00070qA.jpg?1534255016', '[{%22isAnswere%22:true,%22value%22:%22Oui%22},{%22isAnswere%22:false,%22value%22:%22Non%22}]', false, 'La signalisation me permet effectivement de dépasser.', 'La flèche de rabattement ne me concerne pas vu son orientation, et la ligne de dissuasion est liée à cette flèche. Elles annoncent une ligne continue aux usagers circulant dans l%27autre sens.

Mais est-ce le moment de dépasser ? Non ! La visibilité n%27est pas bonne. Je risque d%27être surpris par un usager arrivant en face, surtout si celui-ci est mal éclairé. Comme celui qui me suit par exemple...'),
('envoituresimone.com', '', 2, 30, 'Je dépasse', true, 'image', '2.30.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/212/medium/00070qA.jpg?1534255016', '[{%22isAnswere%22:false,%22value%22:%22Oui%22},{%22isAnswere%22:true,%22value%22:%22Non%22}]', false, 'La signalisation me permet effectivement de dépasser.', 'La flèche de rabattement ne me concerne pas vu son orientation, et la ligne de dissuasion est liée à cette flèche. Elles annoncent une ligne continue aux usagers circulant dans l%27autre sens.

Mais est-ce le moment de dépasser ? Non ! La visibilité n%27est pas bonne. Je risque d%27être surpris par un usager arrivant en face, surtout si celui-ci est mal éclairé. Comme celui qui me suit par exemple...'),
('envoituresimone.com', '', 2, 31, 'Avant de quitter mon véhicule, je vérifie', true, 'image', '2.31.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/215/medium/00071qA.jpg?1534255032', '[{%22isAnswere%22:true,%22value%22:%22le bon serrage du frein de parking%22},{%22isAnswere%22:true,%22value%22:%22qu%27aucun objet convoité n%27est visible%22},{%22isAnswere%22:false,%22value%22:%22Aucun%22}]', true, 'Il y a quelques précautions à prendre systématiquement avant de quitter une voiture.', 'D%27une part, s%27assurer que le frein de parking (le frein à main, aussi appelé frein de parcage) est correctement serré. Même s%27il s%27agit d%27une voiture automatique et que le sélecteur est sur P.

Ensuite, vérifier que toutes les vitres sont remontées totalement.

Vérifier aussi qu%27aucun objet convoité n%27est visible : portefeuille, sacoche d%27ordinateur, GPS (y compris sa ventouse) ou téléphone.

Puis, après être descendu, je m%27assure que les portes sont bien verrouillées.'),
('envoituresimone.com', '', 2, 32, 'Pour accroître la longévité des pneus', true, 'image', '2.32.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/218/medium/00072qA.jpg?1534255048', '[{%22isAnswere%22:false,%22value%22:%22je les surgonfle légèrement%22},{%22isAnswere%22:false,%22value%22:%22je les sous-gonfle légèrement%22},{%22isAnswere%22:true,%22value%22:%22Aucun%22}]', false, 'Pour chaque modèle de voiture, le constructeur a prévu une valeur exacte de gonflage des pneus selon leurs dimensions.', 'Cela permet que l%27adhérence soit la meilleure possible, mais aussi que les pneus ne s%27usent pas trop vite.

Le sous-gonflage comme le surgonflage nuisent à la tenue de route, et entraînent une usure irrégulière et rapide des pneus

Et comme les pneus ne sont pas totalement étanches, je vérifie au moins 1 fois par mois que leur pression est toujours conforme à ce que prévoit le constructeur de la voiture.'),
('envoituresimone.com', '', 2, 33, 'Un chargement qui dépasse l%27arrière de la voiture doit faire l%27objet d%27une signalisation particulière s%27il déborde de', true, 'image', '2.33.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/221/medium/00073qA.jpg?1534255063', '[{%22isAnswere%22:false,%22value%22:%22Moins d%27un mètre%22},{%22isAnswere%22:true,%22value%22:%22Plus d%27un mètre%22}]', false, 'Le chargement d%27un véhicule peut dépasser son aplomb arrière. Alors que c%27est interdit à l%27avant', 'Cependant, il y a une règle. Jusqu%27à 1 mètre, il n%27est pas obligatoire de le signaler (même si cela peut être utile).

Au-delà de 1 mètre, jusqu%27à 3 mètres (le maximum autorisé), une signalisation devient obligatoire. Attention : pas un simple bout de tissu comme on le voit souvent. Il faut un dispositif homologué, réfléchissant, complété d%27une lumière rouge pour circuler de nuit.'),
('envoituresimone.com', '', 2, 34, 'Je tourne à gauche', true, 'image', '2.34.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/224/medium/00074qA.jpg?1534255078', '[{%22isAnswere%22:true,%22value%22:%22je reste dans cette voie%22},{%22isAnswere%22:false,%22value%22:%22je me place dans la voie de gauche%22}]', false, 'La rue dans laquelle je circule est à sens unique.', 'Si je tourne à gauche, où dois-je me placer ?

Il y a 2 voies qui permettent de tourner à gauche. Dans ce cas, je dois me placer dans celle qui est la plus à droite. Je peux utiliser l%27autre voie uniquement dans 2 cas : pour dépasser ou si la voie de droite est encombrée. Mais je ne suis dans aucun de ces 2 cas ici.

Donc je reste dans cette voie pour aller à gauche.'),
('envoituresimone.com', '', 2, 35, 'Tout danger de déraper est écarté', true, 'video', '2.35.mp4', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/videos/attachments/000/000/521/large-mp4/00168qA.mp4?1534257568', '[{%22isAnswere%22:false,%22value%22:%22Oui%22},{%22isAnswere%22:true,%22value%22:%22Non%22}]', false, 'Un usager, sans doute très pressé, a décidé de me dépasser. Peut-être considère-t-il que la route n%27est pas glissante...', 'Que dois-je en penser ?

C%27est vrai que, immédiatement, la route ne présente pas de signe de plaques de neige et qu%27elle ne semble pas gelée... Elle est mouillée, il reste un peu de neige fondue, c%27est vrai, mais pas glissante comme si elle était verglacée.

Sauf que... je ne suis pas à l%27abri que la situation change en quelques mètres seulement. Le sol est autour de 0 degré, peut-être moins... et je risque à tout moment de me faire surprendre par une plaque de verglas isolée. Mieux vaut ne pas suivre l%27exemple de cet automobiliste imprudent !'),
('envoituresimone.com', '', 2, 36, 'Les usagers %22fragiles%22, tels que les piétons ou les utilisateurs de deux-roues représentent environ', true, 'image', '2.36.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/230/medium/00076qA.jpg?1534255113', '[{%22isAnswere%22:false,%22value%22:%225% des tués%22},{%22isAnswere%22:false,%22value%22:%2215% des tués%22},{%22isAnswere%22:false,%22value%22:%2230% des tués%22},{%22isAnswere%22:true,%22value%22:%2240% des tués%22}]', false, 'Chaque année, les usagers %22fragiles%22 (les piétons, les %22deux-roues%22, motorisés ou non) paient un lourd tribut.', 'L%27absence de carrosserie pour les protéger en cas de choc, mais aussi parfois le manque de respect des règles élémentaires leur font courir d%27énormes risques. Ainsi, ils représentent près de 40% des tués sur la route.'),
('envoituresimone.com', '', 2, 37, 'Le système d%27appel d%27urgence (ECall)', true, 'image', '2.37.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/233/medium/00077qA.jpg?1534255127', '[{%22isAnswere%22:true,%22value%22:%22alerte automatiquement les secours en cas d%27accident grave%22},{%22isAnswere%22:true,%22value%22:%22permet de géolocaliser automatiquement l%27accident%22},{%22isAnswere%22:false,%22value%22:%22Aucun%22}]', true, 'Le système d%27appel d%27urgence, appelé aussi %22ECall%22 permet de prévenir les secours depuis la voiture en cas d%27urgence.', 'Soit c%27est un occupant de la voiture qui le déclenche, avec une commande dédiée, et les occupants peuvent alors être en liaison avec un opérateur. Cela permet par exemple de prévenir les secours si l%27on est témoin d%27un accident.

Soit c%27est la voiture seule qui transmet l%27alerte en cas d%27accident grave (détecté par le déclenchement des airbags). Elle transmet alors aussi les coordonnées GPS afin de géolocaliser l%27accident.'),
('envoituresimone.com', '', 2, 38, 'J%27augmente l%27intervalle de sécurité si je circule à', true, 'image', '2.38.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/236/medium/00078qA.jpg?1534255144', '[{%22isAnswere%22:true,%22value%22:%2240 km/h%22},{%22isAnswere%22:true,%22value%22:%2220 km/h%22}]', true, 'La route est très glissante.', 'Aussi, quelle que soit la vitesse à laquelle je circule, j%27augmente l%27intervalle qui me sépare de la voiture devant moi. Cela me permettra d%27envisager un freinage plus sereinement, mais surtout d%27éviter cette voiture si celle-ci se mettait en travers de la route. Surtout que nous sommes dans une descente...'),
('envoituresimone.com', '', 2, 39, 'Je dois m%27arrêter pour proposer de l%27aide', true, 'image', '2.39.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/239/medium/00079qA.jpg?1534255156', '[{%22isAnswere%22:false,%22value%22:%22Oui%22},{%22isAnswere%22:true,%22value%22:%22Non%22}]', false, 'Un accident de la route vient de se produire, comme l%27indique le panneau temporaire.', 'Les secours sont en place, les victimes éventuelles sont donc entre de bonnes mains. Je ne m%27arrête pas, mais je franchis la zone de l%27accident à allure modérée, et surtout en restant très vigilant. Sans quitter la route des yeux.'),
('envoituresimone.com', '', 2, 40, 'Un habitacle trop chaud', true, 'image', '2.40.jpeg', 'https://evs-profilepics.s3.amazonaws.com/production/cdr/images/attachments/000/000/243/medium/00080qA.jpg?1534255178', '[{%22isAnswere%22:true,%22value%22:%22favorise l%27endormissement%22},{%22isAnswere%22:true,%22value%22:%22favorise l%27apparition de la fatigue%22},{%22isAnswere%22:false,%22value%22:%22Aucun%22}]', true, 'Une chaleur excessive dans l%27habitacle (au-delà de 27 degrés) rend le trajet pénible.', 'En conséquence, la fatigue arrive plus vite, ce qui conduit à une somnolence (le temps de réaction augmente) voire à l%27endormissement.

C%27est là que la climatisation devient un véritable accessoire de sécurité plus que de confort. En abaissant la température de quelques degrés, je suis plus vigilant et je réduis le risque d%27être impliqué dans un accident.');

